name: 'Setup Akka CLI'
description: 'Setup and basic configuration of the Akka CLI'
branding:
  color: 'green'
  icon: zap
inputs:
  token:
    #TODO fix docs url
    description: 'Akka refresh token, see: https://doc.akka.io/snapshots/akka-documentation/operations/integrating-cicd/index.html#create_a_service_token'
    required: true
  project-id:
    description: 'Akka project id, check your project id with `akka projects list`'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'